language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION='3.3.*'

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  include:
    - php: 5.5
      env:
        - COMPOSER_FLAGS="--prefer-lowest"
        - SYMFONY_VERSION='2.7.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='2.7.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='2.8.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='3.1.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='3.2.*'
    - php: hhvm
      dist: trusty

before_install:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'

before_script:
  - composer update $COMPOSER_FLAGS

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/simple-phpunit ${PHPUNIT_FLAGS}
