language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    # Minimum supported dependencies with min and max PHP version
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

    # Latest supported dependencies with each PHP version
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

    - php: 7.4
      env: SYMFONY_REQUIRE=4.3.*
    - php: 7.4
      env: SYMFONY_REQUIRE=4.4.*
    - php: 7.4
      env: SYMFONY_REQUIRE=5.0.*

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak ./vendor/bin/simple-phpunit ${PHPUNIT_FLAGS}
